[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-L", "/usr/lib/gcc-cross/x86_64-linux-gnu/12/"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-L", "/usr/lib/gcc/aarch64-linux-gnu/12/"]

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-L", "/usr/lib/gcc-cross/riscv64-linux-gnu/12/"]
